capitalone/react-native-pathjs-charts

README.md
example/package.json
package.json

This fix also includes guidance to link the react-native-svg library directly.
Signed-off-by: Cale Hoopes <caledh@gmail.com>

Fixing to work with RN 0.30 and RNSVG 3.1.1

---

package.json

The react-native-svg has been updated to compile with last version of react-native (0.34.1).

Fix version of react-native-svg

---

src/Line.js

This allows user to define showAreas property in options of line type charts. Default value(if undefined) is true.

adds showAreas prop - allows user to define if areas are shown

---

example/ios/example.xcodeproj/project.pbxproj
example/package.json
package.json

Fixes issue #6 
Adding c++ linker flag was necessary to avoid build errors - [one comment](https://github.com/facebook/react-native/issues/7532#issuecomment-223046991), among several others found, helped address this issue.

Fix broken example app by upgrading to React Native 0.35 and adding c++ linker flag

---

README.md
example/data.js

Fix documentation for pie diagram

Fix documentation for #8

---

.gitignore
README.md
util/watchman-update-example-src/README.md
util/watchman-update-example-src/create-script-from-template.sh
util/watchman-update-example-src/script-template

Scripts to setup a [Watchman](https://facebook.github.io/watchman/)-based file watch that automates source file copying between the project source and the example app to make manual testing easier

Added watchman-update-example-src script to ease manual testing

---

example/package.json
package.json
src/Axis.js
src/Bar.js
src/Line.js
src/Tree.js

Fix #26 
- Axis component used on StockLine, SmoothLine, and Scatterplot charts now handles margin/offset properly
- When changes are made to the margin options for these types of charts, charts should now display properly (where before offset would affect chart drawing area but not axes/gridlines)
- Modified Bar chart to fix display problems with labels along x-axis (removed 25 offset value)
- Removed unnecessary embedded G SVG grouping tag (to previously address offset handling) on StockLine & SmoothLine charts that was causing display problems
- Removed unnecessary embedded G SVG grouping tag (to previously address offset handling) on Tree chart

Fixed #26 - axes now respect offsets properly and cleanup of other offset

---

example/package.json
package.json

Updating versions to be compatible with the required react-native-svg (4.4.1) version that is being used by react-native-pathjs-charts.

Update react and react-native versions

---

example/package.json
package.json

After attempting to upgrade to newer versions of react-native-svg (and also react-native), I found rendering problems on the charts in the example app:
- When switching to react-native-svg 4.6.1 and react-native 0.40.0, a number of charts replace the (blue colored) grid lines with bold black lines and the radar chart didn't render some of its (blue) lines at all
- Switching to react-native-svg 5.14 (also using  react-native 0.40.0), all of the chart problems above are fixed but then the bar chart is missing its labels due to a new text rotation bug in react-native-svg - https://github.com/react-native-community/react-native-svg/issues/242
Also, unfortunately we are using caret semver ranges in package.json for both react-native and react-native-svg which means that a person cloning this …

Pinning to patch-updates only for react-native and react-native-svg

---

src/Pie.js
src/__mocks__/react-native-svg.js
src/__tests__/PieBasic-test.js
src/__tests__/__snapshots__/PieBasic-test.js.snap

Fixes #20 so that a single-item pie chart renders correctly now.
This was a bit tricky as it was a bit unexpected that an arc with the same start and ending point renders nothing in svg as opposed to rendering a complete circle (which seems more natural from an end-user standpoint but maybe not natural from a pure mathematical standpoint). This issue is discussed in [this StackOverflow question](http://stackoverflow.com/questions/5737975/circle-drawing-with-svgs-arc-path). 
The paths-js library which this library depends on directly to provide the svg paths to draw the pie chart doesn't have any special handling for a complete-circle arc either. So, I took the approach of looking specifically for the scenario where there was only 1 data item and substituting react-native-svg `<Circle>`s - …

Fixed #20 - renders single-item pie chart correctly now

---

example/package.json
example/src/App.js

Fix #62 - adding Babel polyfill to fix undefined not a function error

---

example/.babelrc

This is intentionally redundant with the .babelrc in the root of the project. The one in example fixes issue #63 when running the example while the one in the root allows `npm test` (jest) to run successfully.

Fix #63 - adding babelrc config file to example

---

src/Radar.js

Hi, I have added a few lines regarding the color management in the radar chart.
It checks if the fill property is an array and deals with it by using one color for each render or the colors specified.
The previous behavior is still working.

Add color management to Radar chart

---

package.json
src/Bar.js
src/Pie.js
src/Radar.js
src/Scatterplot.js
src/Tree.js

Fixes #62 for users of the library targeting Android

Adding babel-polyfill import to many charts to fix #62 for Android

---

src/Bar.js

The original (broken) implementation uses a svg group around the x axis
text label. The x and y coordinates for that svg group are driven off
the chart's margin left and top offset values respectively. The
implication of this is that when specifying left and/or top offsets for
the entire chart, it inadvertently makes the labels either not aligned
with its corresponding bars (if the margin left value is too big) or
makes the labels appear way below the x axis or not at all (if the
margin top value is too big).
This fix removes the seemingly unnecessary svg grouping with incorrect
positioning around the label and modifies the y value for the label. The
x value (which is the center of the label) remains positioned at the
center of the bar above that it corresponds with. The y value has been …

Fix #103 - cleanup x axis label offsets to avoid tie to chart offsets

---

src/Bar.js

Change from hardcoded number (`3`) modded to chose bar color from a 9-color palette to one that targets the length of the number of groups in the input data set (but maintains the color variation if there is just one group as before).

Fixes #134 - allowing bar coloring to respect grouped data

---

src/Pie.js

* Fix NaN x/y values if `options` prop is supplied but does not contain margins
* Fix centering - before this change centering applied two times and `center` option actually meant "x and y shift from the center" instead of "x and y position of the actual center".
* Fix centering if only one data object is provided. Center option was ignored in`this.props.data.length === 1` codepath.
* Do not create actual pie chart object if we have only 1 data object because we render Circle instead.

Fix pie chart centering

---

circle.yml
example/.babelrc
example/.flowconfig
example/.gitignore
example/android/app/BUCK
example/android/app/build.gradle
example/android/app/proguard-rules.pro
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/java/com/example/MainApplication.java
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/keystores/BUCK
example/ios/exampleTests/exampleTests.m
example/package.json
example/src/App.js
example/src/bar/BarChartColumnBasic.js
example/src/pie/PieChartBasic.js
example/src/radar/RadarChartBasic.js
example/src/scatterplot/ScatterplotChartBasic.js
example/src/smoothline/SmoothLineChartBasic.js
example/src/smoothline/SmoothLineChartRegions.js
example/src/smoothline/SmoothLineChartRegionsExtended.js
example/src/stockline/StockLineChartBasic.js
example/src/stockline/StockLineChartDynamicTickLabels.js
example/src/stockline/StockLineChartStaticTickLabels.js
example/src/tree/TreeChartBasic.js
package.json
src/Bar.js

There were several changes here getting things up to latest versions of react, react-native, and react-native-svg:
- The newest version of react-native deprecated the old style of navigation we were using in the example app. I did away with the side menu navigation and created a quick simple navigation scheme driven off the initial main screen when the app launches. It is not that pretty and needs styling but this is fine for now
- react-native-svg required two changes to make it "work" with the latest version:
- had to add originX/originY on bar chart in order to make text rotation work like it did previously
- embedded newlines in the dynamic label stockline chart no longer renders correctly with this latest version, so I decided to make the labels just have a time portion instead of …

Update to latest react, react-native, and react-native-svg versions

---

src/Axis.js

Thank you for contributing a pull request. 
Please ensure that you have signed the [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform).
Fixed issue #136

Added options for axis tick size and color

---

example/src/radar/RadarChartBasic.js
src/Axis.js
src/Radar.js
src/util.js

Thank you for contributing a pull request. 
Please ensure that you have signed the [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform).
https://github.com/capitalone/react-native-pathjs-charts/issues/161

Add on press radar chart

---

example/package.json
package.json

Thank you for contributing a pull request. 
Please ensure that you have signed the [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform).
- [✓ ] I have signed the CLA

Fix the RN 0.46 and above incompatibility issues caused by React Native SVG 5.2

---

CHANGELOG.md
package.json

New release for .31

---

src/Axis.js
src/Bar.js
src/GridAxis.js
src/Line.js
src/Scatterplot.js
src/__tests__/SmoothLine/__snapshots__/SmoothLineBasic-test.js.snap
src/__tests__/SmoothLine/__snapshots__/SmoothLineRegions-test.js.snap
src/__tests__/SmoothLine/__snapshots__/SmoothLineRegionsExtended-test.js.snap
src/__tests__/scatterplot/__snapshots__/ScatterplotBasic-test.js.snap
src/__tests__/stockline/__snapshots__/StockLineBasic-test.js.snap
src/__tests__/stockline/__snapshots__/StockLineDynamicTickLabels-test.js.snap
src/__tests__/stockline/__snapshots__/StockLineStaticTickLabels-test.js.snap

Thank you for contributing a pull request. 
Please ensure that you have signed the [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform).

Fix grid axis appearing on top of the lines

---

example/src/App.js
package.json
src/Bar.js
src/Pie.js
src/Radar.js
src/Scatterplot.js
src/Tree.js
src/index.js

This addresses the great feedback provided by @phillbaker in #173. As he pointed out, this fix should also address #195 and #202 as well.

Removed babel-polyfill and substituted with narrower imports

---

example/src/App.js
example/src/stockline/StockLineChartGesture.js
src/Line.js
src/SmoothLine.js
src/StockLine.js

React-native-pathjs-charts team:
Hey, I was using your chart library for a while. Really handy stock charts to use and I love it.
I worked on chart interaction and tried to implement gesture on line to meet my own project requirement. And I just cleaned it up a little bit and want to share my stuff. This commit add a property `interaction` which default to false. When turn to true. It will response with gesture. 
We can specify call back function in `panHandlerStart`, `panHandlerMove`, `panHandlerEnd`. Each for different stage of gesture.
It also have another feature called `cursorLine` default as `red` color with `width = 1`, which will show as a vertical line on top of the chart as a cursor to indicate while the finger is pressing.
Let me know what you think.
Thank you for contributing …

feature: add interaction on line chart.
